-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 19:15:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_editorial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_editorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_editorial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_editorial` ;

-- -----------------------------------------------------
-- Table `bd_editorial`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`especialidades` (
  `id_especialidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_especialidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`editoriales` (
  `id_editorial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_editorial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`periodistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`periodistas` (
  `id_periodista` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(75) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `nit` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `id_especialidad` INT NOT NULL,
  `id_editorial` INT NOT NULL,
  PRIMARY KEY (`id_periodista`),
  UNIQUE INDEX `nit` (`nit` ASC) VISIBLE,
  INDEX `id_especialidad` (`id_especialidad` ASC) VISIBLE,
  INDEX `id_editorial` (`id_editorial` ASC) VISIBLE,
  CONSTRAINT `periodistas_ibfk_1`
    FOREIGN KEY (`id_especialidad`)
    REFERENCES `bd_editorial`.`especialidades` (`id_especialidad`),
  CONSTRAINT `periodistas_ibfk_2`
    FOREIGN KEY (`id_editorial`)
    REFERENCES `bd_editorial`.`editoriales` (`id_editorial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`periodicidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`periodicidades` (
  `id_periodicidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_periodicidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`tipos_revistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`tipos_revistas` (
  `id_tipo_revista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_revista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`revistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`revistas` (
  `id_revista` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `numero_registro` VARCHAR(255) NOT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `numero_paginas` INT NOT NULL,
  `cantidad_vendidas` INT NOT NULL,
  `id_periodicidad` INT NOT NULL,
  `id_tipo_revista` INT NOT NULL,
  PRIMARY KEY (`id_revista`),
  UNIQUE INDEX `numero_registro` (`numero_registro` ASC) VISIBLE,
  INDEX `id_periodicidad` (`id_periodicidad` ASC) VISIBLE,
  INDEX `id_tipo_revista` (`id_tipo_revista` ASC) VISIBLE,
  CONSTRAINT `revistas_ibfk_1`
    FOREIGN KEY (`id_periodicidad`)
    REFERENCES `bd_editorial`.`periodicidades` (`id_periodicidad`),
  CONSTRAINT `revistas_ibfk_2`
    FOREIGN KEY (`id_tipo_revista`)
    REFERENCES `bd_editorial`.`tipos_revistas` (`id_tipo_revista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `contenido` TEXT NOT NULL,
  `id_periodista` INT NOT NULL,
  `id_revista` INT NOT NULL,
  PRIMARY KEY (`id_articulo`),
  INDEX `id_periodista` (`id_periodista` ASC) VISIBLE,
  INDEX `id_revista` (`id_revista` ASC) VISIBLE,
  CONSTRAINT `articulos_ibfk_1`
    FOREIGN KEY (`id_periodista`)
    REFERENCES `bd_editorial`.`periodistas` (`id_periodista`),
  CONSTRAINT `articulos_ibfk_2`
    FOREIGN KEY (`id_revista`)
    REFERENCES `bd_editorial`.`revistas` (`id_revista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`municipios` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`direcciones` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `direccion_completa` VARCHAR(255) NOT NULL,
  `id_municipio` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `id_municipio` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `direcciones_ibfk_1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `bd_editorial`.`municipios` (`id_municipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`sucursales` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `codigo` VARCHAR(50) NOT NULL,
  `id_editorial` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  PRIMARY KEY (`id_sucursal`),
  UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE,
  INDEX `id_editorial` (`id_editorial` ASC) VISIBLE,
  INDEX `id_direccion` (`id_direccion` ASC) VISIBLE,
  CONSTRAINT `sucursales_ibfk_1`
    FOREIGN KEY (`id_editorial`)
    REFERENCES `bd_editorial`.`editoriales` (`id_editorial`),
  CONSTRAINT `sucursales_ibfk_2`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `bd_editorial`.`direcciones` (`id_direccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(75) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `nit` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `nit` (`nit` ASC) VISIBLE,
  INDEX `id_sucursal` (`id_sucursal` ASC) VISIBLE,
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `bd_editorial`.`sucursales` (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`revistas_sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`revistas_sucursales` (
  `id_revista_sucursal` INT NOT NULL AUTO_INCREMENT,
  `id_revista` INT NOT NULL,
  `id_sucursal` INT NOT NULL,
  PRIMARY KEY (`id_revista_sucursal`),
  INDEX `id_revista` (`id_revista` ASC) VISIBLE,
  INDEX `id_sucursal` (`id_sucursal` ASC) VISIBLE,
  CONSTRAINT `revistas_sucursales_ibfk_1`
    FOREIGN KEY (`id_revista`)
    REFERENCES `bd_editorial`.`revistas` (`id_revista`),
  CONSTRAINT `revistas_sucursales_ibfk_2`
    FOREIGN KEY (`id_sucursal`)
    REFERENCES `bd_editorial`.`sucursales` (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`secciones` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `extension` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_editorial`.`secciones_revistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_editorial`.`secciones_revistas` (
  `id_seccion_revista` INT NOT NULL AUTO_INCREMENT,
  `id_seccion` INT NOT NULL,
  `id_revista` INT NOT NULL,
  PRIMARY KEY (`id_seccion_revista`),
  INDEX `id_seccion` (`id_seccion` ASC) VISIBLE,
  INDEX `id_revista` (`id_revista` ASC) VISIBLE,
  CONSTRAINT `secciones_revistas_ibfk_1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `bd_editorial`.`secciones` (`id_seccion`),
  CONSTRAINT `secciones_revistas_ibfk_2`
    FOREIGN KEY (`id_revista`)
    REFERENCES `bd_editorial`.`revistas` (`id_revista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
